"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var zia = " sir zia khan";
var msg = ("Hello! I would like to learn Typescript");
console.log(zia, msg);
let name1 = "Zubair";
let message = `Hello ${name1} , would you like to learn some Python today?`;
console.log(message);
console.log(`"how are you"`);
console.log(`how are you`);
