"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
let a = 4;
let b = 4;
console.log(a + b);
a = 16;
b = 8;
console.log(a - b);
a = 16;
b = 2;
console.log(a / b);
a = 4;
b = 2;
console.log(a * b);
