"use strict";
var userName = " Zubair khan Hello world";
console.log(userName);
var num1 = 2;
var num2 = 3;
var num3 = 4;
var result = num1 + num2 + num3;
var result1 = num1 * num2 * num3;
var result2 = num1 / num2 / num3;
console.log(result, result1, result2);
